export const RELOAD_EMPLOYEE_PAGE = 'RELOAD_EMPLOYEE_PAGE';
export const UPDATE_EMPLOYEE_INFORMATION = 'UPDATE_EMPLOYEE_INFORMATION';
export const GET_DETAIL_NOTIFICATION__SYSTEM_EMPLOYEE = "GET_DETAIL_NOTIFICATION__SYSTEM_EMPLOYEE";