export const PASS_DATA_FROM_FORM_TO_MODAL_IN_CREATE_ACCOUNT_ADMIN = 'PASS_DATA_FROM_FORM_TO_MODAL_IN_CREATE_ACCOUNT_ADMIN';
export const LOAD_TABLE_AFTER_REJECT = 'LOAD_TABLE_AFTER_REJECT';
export const UPDATE_ID_DEPARTMENT_SEARCH = 'UPDATE_ID_DEPARTMENT_SEARCH';
export const UPDATE_ID_DEPARTMENT_ASSIGN = 'UPDATE_ID_DEPARTMENT_ASSIGN';
export const UPDATE_PROCESS_INFORMATION = 'UPDATE_PROCESS_INFORMATION';
export const RESET_PROCESS_INFORMATION = 'RESET_PROCESS_INFORMATION';
