export const PASS_POPUP_STATUS = 'PASS_POPUP_STATUS';
export const ADD_AND_UPDATE_ELEMENTS = 'ADD_AND_UPDATE_ELEMENTS';
export const SAVE_NOTE_FOR_ELEMENT = 'SAVE_NOTE_FOR_ELEMENT';
export const DELETE_NOTE_FOR_ELEMENT = 'DELETE_NOTE_FOR_ELEMENT';
export const SAVE_COMMENT_FOR_ELEMENT = 'SAVE_COMMENT_FOR_ELEMENT';
export const DELETE_COMMENT_OF_ELEMENT = 'DELETE_COMMENT_OF_ELEMENT';
export const DELETE_ELEMENT = 'DELETE_ELEMENT';
export const HANDLE_UNDO_AFTER_DELETE_ELEMENT = 'HANDLE_UNDO_AFTER_DELETE_ELEMENT';
export const SAVE_DIAGRAM = 'SAVE_DIAGRAM';
export const EDIT_DIAGRAM = 'EDIT_DIAGRAM';
export const EXPORT_DIAGRAM_AS_SVG = 'EXPORT_DIAGRAM_AS_SVG';
export const EXPORT_DIAGRAM_AS_IMAGE = 'EXPORT_DIAGRAM_AS_IMAGE';
export const EXPORT_DIAGRAM_AS_BPMN = 'EXPORT_DIAGRAM_AS_BPMN';
export const EXTRACTDATAELEMENTWHENEDIT = 'EXTRACTDATAELEMENTWHENEDIT';
export const CHANGEHEADERSTATUSTOEDIT = 'CHANGEHEADERSTATUSTOEDIT';
export const UPDATEIMPORTBPMNFILE = 'UPDATEIMPORTBPMNFILE';
export const RESETIMPORTBPMNFILE = 'RESETIMPORTBPMNFILE';
export const EXPORT_DIAGRAM_AS_SVG_EDIT = 'EXPORT_DIAGRAM_AS_SVG_EDIT';
export const EXPORT_DIAGRAM_AS_IMAGE_EDIT = 'EXPORT_DIAGRAM_AS_IMAGE_EDIT';
export const EXPORT_DIAGRAM_AS_BPMN_EDIT = 'EXPORT_DIAGRAM_AS_BPMN_EDIT';
export const RESETACTIONTODIAGRAM = 'RESETACTIONTODIAGRAM';
export const UPDATEASSIGNEDEMPLOYEEFORELEMENT = 'UPDATEASSIGNEDEMPLOYEEFORELEMENT';
export const RESETASSIGNEDEMPLOYEEFORELEMENT = 'RESETASSIGNEDEMPLOYEEFORELEMENT';
export const UPDATEDEFAULTASSIGNEDEMPLOYEEFORELEMENT = 'UPDATEDEFAULTASSIGNEDEMPLOYEEFORELEMENT';
export const RESETDEFAULTASSIGNEDEMPLOYEEFORELEMENT = 'RESETDEFAULTASSIGNEDEMPLOYEEFORELEMENT';
export const UPDATENAMEOFELEMENT = 'UPDATENAMEOFELEMENT';
export const CHANGEISSAVENOTETOFALSE = 'CHANGEISSAVENOTETOFALSE';
export const UPDATE_FILE_TEMPLATES_FOR_PROCESS = 'UPDATE_FILE_TEMPLATES_FOR_PROCESS';
export const UPDATE_FILE_TEMPLATES_IN_EDIT_PROCESS = 'UPDATE_FILE_TEMPLATES_IN_EDIT_PROCESS';
export const CLICK_OPEN_MODAL_EDIT_PROCESS_INFO = 'CLICK_OPEN_MODAL_EDIT_PROCESS_INFO';






