export const PASS_POPUP_STATUS = 'PASS_POPUP_STATUS';
export const ADD_AND_UPDATE_ELEMENTS = 'ADD_AND_UPDATE_ELEMENTS';
export const SAVE_NOTE_FOR_ELEMENT = 'SAVE_NOTE_FOR_ELEMENT';
export const DELETE_NOTE_FOR_ELEMENT = 'DELETE_NOTE_FOR_ELEMENT';
export const SAVE_COMMENT_FOR_ELEMENT = 'SAVE_COMMENT_FOR_ELEMENT';
export const DELETE_COMMENT_OF_ELEMENT = 'DELETE_COMMENT_OF_ELEMENT';
export const DELETE_ELEMENT = 'DELETE_ELEMENT';
export const HANDLE_UNDO_AFTER_DELETE_ELEMENT = 'HANDLE_UNDO_AFTER_DELETE_ELEMENT';
export const SAVE_DIAGRAM = 'SAVE_DIAGRAM';
export const EXPORT_DIAGRAM_AS_SVG = 'EXPORT_DIAGRAM_AS_SVG';
export const EXPORT_DIAGRAM_AS_IMAGE = 'EXPORT_DIAGRAM_AS_IMAGE';
export const EXPORT_DIAGRAM_AS_BPMN = 'EXPORT_DIAGRAM_AS_BPMN';
export const RESET_ACTION_STATES = 'RESET_ACTION_STATES';





