// MANAGER DEPARTMENT IN ORANIZATION
export const SHOW_EDIT_DEPARTMENT = 'SHOW_EDIT_DEPARTMENT';
export const DETAIL_DEPARTMENT= 'DETAIL_DEPARTMENT';
export const HIDE_EDIT_DEPARTMENT = 'HIDE_EDIT_DEPARTMENT';
export const SHOW_NEW_DEPARTMENT = 'SHOW_NEW_DEPARTMENT';
export const HIDE_NEW_DEPARTMENT = 'HIDE_NEW_DEPARTMENT';

// MANAGER USER IN ORGANIZATION

export const ADD_USER = 'ADD_USERT';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';
export const DETAIL_USER = 'DETAIL_USER';
export const SHOW_EDIT_USER = 'SHOW_EDIT_USER';
export const HIDE_EDIT_USER = 'HIDE_EDIT_USER';
export const SHOW_NEW_USER = 'SHOW_NEW_USER';
export const HIDE_NEW_USER = 'HIDE_NEW_USER';