// MANAGER DEPARTMENT IN ORANIZATION
export const SHOW_EDIT_DEPARTMENT = 'SHOW_EDIT_DEPARTMENT';
export const DETAIL_DEPARTMENT= 'DETAIL_DEPARTMENT';
export const HIDE_EDIT_DEPARTMENT = 'HIDE_EDIT_DEPARTMENT';
export const SHOW_NEW_DEPARTMENT = 'SHOW_NEW_DEPARTMENT';
export const HIDE_NEW_DEPARTMENT = 'HIDE_NEW_DEPARTMENT';

// MANAGER USER IN ORGANIZATION

export const SHOW_EDIT_EMPLOYEE = 'SHOW_EDIT_EMPLOYEE';
export const DETAIL_EMPLOYEE= 'DETAIL_EMPLOYEE';
export const HIDE_EDIT_EMPLOYEE = 'HIDE_EDIT_EMPLOYEE';
export const SHOW_NEW_EMPLOYEE = 'SHOW_NEW_EMPLOYEE';
export const HIDE_NEW_EMPLOYEE = 'HIDE_NEW_EMPLOYEE';

// MANAGER ROLE IN ORGANIZATION

export const SHOW_EDIT_ROLE = 'SHOW_EDIT_ROLE';
export const DETAIL_ROLE= 'DETAIL_ROLE';
export const HIDE_EDIT_ROLE = 'HIDE_EDIT_ROLE';
export const SHOW_NEW_ROLE = 'SHOW_NEW_ROLE';
export const HIDE_NEW_ROLE = 'HIDE_NEW_ROLE';
