// MANAGER DEPARTMENT IN ORANIZATION
export const ADD_DEPARMENT = 'ADD_DEPARMENT';
export const DELETE_DEPARMENT = 'DELETE_DEPARMENT';
export const EDIT_DEPARMENT = 'EDIT_DEPARMENT';
export const DETAIL_DEPARMENT = 'DETAIL_DEPARMENT';
export const SHOW_EDIT_DEPARMENT = 'SHOW_EDIT_DEPARMENT';
export const HIDE_EDIT_DEPARMENT = 'HIDE_EDIT_DEPARMENT';
export const SHOW_NEW_DEPARMENT = 'SHOW_NEW_DEPARMENT';
export const HIDE_NEW_DEPARMENT = 'HIDE_NEW_DEPARMENT';

// MANAGER USER IN ORGANIZATION

export const ADD_USER = 'ADD_USERT';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';
export const DETAIL_USER = 'DETAIL_USER';
export const SHOW_EDIT_USER = 'SHOW_EDIT_USER';
export const HIDE_EDIT_USER = 'HIDE_EDIT_USER';
export const SHOW_NEW_USER = 'SHOW_NEW_USER';
export const HIDE_NEW_USER = 'HIDE_NEW_USER';